Ruby on Rails capstone project - Budget app
rtonata88/budget-tracker pull request #1
Opened 2022-04-28 20:27 UTC by rtonata88

In the PR I have implemented all the features for the App with the following screens:

- Splash screen: A simple page with the name of the app.
- Sign up and log in pages
- Home page (catagories page)
- Expenses page
- "Add a new category" page
- "Add a new expense" page

2022-04-28 21:03 UTC, DeliceLydia requested changes
## Hi @rtonata88, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Highlights for your project:
- App is working as expected
- Awesome README
- No linter errors


## Required Changes ♻️
_Check the comments under the review._



### You Rock!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-04-28 21:03 UTC, DeliceLydia commented on app/views/expenses/index.html.erb
> +<%= link_to "New expense", new_expense_path %>
- [ ] All buttons should have a color like in the design `#5fb523` and please follow the given [design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=)

2022-04-28 21:03 UTC, DeliceLydia commented on app/views/expenses/index.html.erb
> +<%= link_to "New expense", new_expense_path %>
- [ ] Design of your application should follow the given one:
- Colors
- Typography: font face, size and weight.
- Layout: composition and space between elements.

2022-04-28 21:03 UTC, DeliceLydia commented on README.md
> +- LinkedIn: [Richard Chambula](https://www.linkedin.com/in/richard-chambula-49198425/)
- [ ] Please deploy your applications and add a live demo in your README

2022-04-29 19:57 UTC, Rustamxon7 approved these changes
## Hello @rtonata88 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-29 19:57 UTC, Rustamxon7 commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] [OPTIONAL] You have added the MIT license link in the readme but there is no MIT.md file itself. So please add the license file also 👍

2022-04-29 19:57 UTC, Rustamxon7 commented on README.md
- [ ] [OPTIONAL] Let's also add the screenshot of your app also 📷 to the readme file 📃.

2022-04-29 21:34 UTC, merged